services:
  mongoDB:
    image: mongo:8.3.8-noble
    container_name: mongoDB

    ports:
      - "27017:27017"

    volumes:
      - mongo_data:/data/db

    healthcheck:
      test: [ "CMD", "mongosh", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:8.10.0-alpine
    container_name: redis

    ports:
      - "6379:6379"

    volumes:
      - redis_data:/data

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10

  expressAppContainer:
    container_name: expressAppContainer

    build:
      context: .
      dockerfile: Dockerfile.dev

    image: petshop_backend:dev

    ports:
      - "8080:8080"

    env_file:
      - .env.dev

    depends_on:
      mongoDB:
        condition: service_healthy
      redis:
        condition: service_healthy

    volumes:
      - ./src:/app/src
    
    cpus: 2
    mem_limit: 4g
    mem_reservation: 2g

  mongoExpress:
    container_name: mongoExpress
    image: mongo-express:latest

    ports:
      - "8081:8081"

    environment:
      ME_CONFIG_MONGODB_SERVER: mongoDB
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin

    depends_on:
      mongoDB:
        condition: service_healthy

volumes:
  mongo_data:
  redis_data:
