import { METHODS } from './constants.js';

const { get, post, put, patch, delete: deleteMethod } = METHODS;

export const API_ROUTE_METHODS = [
  { path: '/users', methods: [post] },
  { path: '/users/register', methods: [post] },
  { path: '/users/send-otp', methods: [post] },
  { path: '/users/verify', methods: [post] },
  { path: '/users/reset-password', methods: [post] },
  { path: '/users/login', methods: [post] },
  { path: '/users/refresh-token', methods: [post] },
  { path: '/users/edit-info', methods: [put] },
  { path: '/users/addresses', methods: [get, post] },
  { path: '/users/addresses/:addressId', methods: [patch] },
  { path: '/users/change-password', methods: [put] },
  { path: '/users/disable/:id', methods: [put] },
  { path: '/users/enable/:id', methods: [put] },
  { path: '/users/all', methods: [get] },
  { path: '/users/paginate', methods: [get] },
  { path: '/users/:id', methods: [get, deleteMethod] },
  { path: '/cart/add', methods: [post] },
  { path: '/cart/delete/:id', methods: [deleteMethod] },
  { path: '/cart/all', methods: [get] },
  { path: '/cart/empty', methods: [deleteMethod] },
  { path: '/wishlist/add', methods: [post] },
  { path: '/wishlist/delete/:id', methods: [deleteMethod] },
  { path: '/wishlist/all', methods: [get] },
  { path: '/pet-types', methods: [get, post] },
  { path: '/pet-types/slug/:slug', methods: [get] },
  { path: '/pet-types/:id', methods: [get, put, deleteMethod] },
  { path: '/pet-types/:id/disable', methods: [patch] },
  { path: '/pet-types/:id/enable', methods: [patch] },
  { path: '/categories', methods: [get, post] },
  { path: '/categories/enable/:id', methods: [put] },
  { path: '/categories/disable/:id', methods: [put] },
  { path: '/categories/:id', methods: [get, put, deleteMethod] },
  { path: '/sub-categories', methods: [get, post] },
  { path: '/sub-categories/:id', methods: [get, put, deleteMethod] },
  { path: '/breeds', methods: [get, post] },
  { path: '/breeds/paginate', methods: [get] },
  { path: '/breeds/:id', methods: [get, put, deleteMethod] },
  { path: '/breeds/:id/enable', methods: [patch] },
  { path: '/breeds/:id/disable', methods: [patch] },
  { path: '/pets', methods: [get, post] },
  { path: '/pets/customer/paginate', methods: [get] },
  { path: '/pets/customer/:id', methods: [get] },
  { path: '/pets/paginate', methods: [get] },
  { path: '/pets/manage/:id', methods: [get] },
  { path: '/pets/:id', methods: [put, deleteMethod] },
  { path: '/pets/:id/images', methods: [get, put] },
  { path: '/pets/:id/price', methods: [get, put] },
  { path: '/pets/:id/base-info', methods: [get] },
  { path: '/pets/:id/enable', methods: [patch] },
  { path: '/pets/:id/disable', methods: [patch] },
  { path: '/products', methods: [get, post] },
  { path: '/products/customer/:id', methods: [get] },
  { path: '/products/paginate', methods: [get] },
  { path: '/products/manage/:id', methods: [get] },
  { path: '/products/:id', methods: [put, patch, deleteMethod] },
  { path: '/products/:id/images', methods: [get, put] },
  { path: '/products/:id/price', methods: [get, put] },
  { path: '/products/:id/main-info', methods: [get, put] },
  { path: '/products/:id/enable', methods: [patch] },
  { path: '/products/:id/disable', methods: [patch] },
  { path: '/orders', methods: [get, post] },
  { path: '/orders/all', methods: [get] },
  { path: '/orders/:id', methods: [get] },
  { path: '/orders/:id/delivery-state', methods: [patch] },
  { path: '/orders/:id/shipping-info', methods: [patch] },
  { path: '/countries', methods: [get] },
  { path: '/provinces', methods: [get] },
  { path: '/cities/:provinceId', methods: [get] },
  { path: '/reverse-geocode', methods: [get] },
  { path: '/otp-code', methods: [post] },
];
