import { METHODS } from './constants.js';

import { BRAND_ROUTES } from '#entities/brands/route.path.js';
import { BREED_ROUTES } from '#entities/breeds/route.path.js';
import { CATEGORY_ROUTES } from '#entities/categories/route.path.js';
import { DASHBOARD_ROUTES } from '#entities/dashboard/route.path.js';
import { IMAGE_ROUTES } from '#entities/images/route.path.js';
import { LANDING_ROUTES } from '#entities/landing/route.path.js';
import { ORDER_ROUTES } from '#entities/orders/route.path.js';
import { PET_ROUTES } from '#entities/pets/route.path.js';
import { PET_TYPE_ROUTES } from '#entities/petTypes/route.path.js';
import { PRODUCT_ROUTES } from '#entities/products/route.path.js';
import { SUB_CATEGORY_ROUTES } from '#entities/subCategories/route.path.js';
import { USER_ROUTES } from '#entities/users/route.path.js';

import { COUNTRY_ROUTES } from '../integrations/countries/route.path.js';
import { LOCATION_ROUTES } from '../integrations/locations/route.path.js';
import { OTP_CODE_ROUTES } from '../integrations/otpCode/route.path.js';
import { REVERSE_GEOCODING_ROUTES } from '../integrations/reverseGeocoding/route.path.js';

const { get, post, put, patch, delete: deleteMethod } = METHODS;

export const API_ROUTE_METHODS = [
  { path: LANDING_ROUTES.landingBrandsPopular, methods: [get] },
  { path: LANDING_ROUTES.landingPetTypesAll, methods: [get] },
  { path: LANDING_ROUTES.landingPetsPopular, methods: [get] },
  { path: LANDING_ROUTES.landingPetsRecent, methods: [get] },
  { path: LANDING_ROUTES.landingProductsDiscounted, methods: [get] },
  { path: LANDING_ROUTES.landingProductsFeatured, methods: [get] },
  { path: LANDING_ROUTES.landingProductsPopular, methods: [get] },
  { path: PET_ROUTES.petsCustomerPaginate, methods: [get] },
  { path: BRAND_ROUTES.brandsByIdDisable, methods: [patch] },
  { path: BRAND_ROUTES.brandsByIdEnable, methods: [patch] },
  { path: BREED_ROUTES.breedsByIdDisable, methods: [patch] },
  { path: BREED_ROUTES.breedsByIdEnable, methods: [patch] },
  { path: BREED_ROUTES.breedsPropertyDefinitionsById, methods: [get] },
  { path: BREED_ROUTES.breedsSlugBySlug, methods: [get] },
  { path: USER_ROUTES.cartDeleteById, methods: [deleteMethod] },
  { path: CATEGORY_ROUTES.categoriesDisableById, methods: [put] },
  { path: CATEGORY_ROUTES.categoriesEnableById, methods: [put] },
  { path: LANDING_ROUTES.landingPetsBySlug, methods: [get] },
  { path: LANDING_ROUTES.landingProductsBySlug, methods: [get] },
  { path: ORDER_ROUTES.ordersByIdDeliveryState, methods: [patch] },
  { path: ORDER_ROUTES.ordersByIdShippingInfo, methods: [patch] },
  { path: PET_TYPE_ROUTES.petTypesByIdDisable, methods: [patch] },
  { path: PET_TYPE_ROUTES.petTypesByIdEnable, methods: [patch] },
  { path: PET_TYPE_ROUTES.petTypesPropertyDefinitionsById, methods: [get] },
  { path: PET_TYPE_ROUTES.petTypesSlugBySlug, methods: [get] },
  { path: PET_ROUTES.petsByIdBaseInfo, methods: [get] },
  { path: PET_ROUTES.petsByIdDisable, methods: [patch] },
  { path: PET_ROUTES.petsByIdEnable, methods: [patch] },
  { path: PET_ROUTES.petsByIdImages, methods: [get, put] },
  { path: PET_ROUTES.petsByIdPrice, methods: [get, put] },
  { path: PET_ROUTES.petsByIdUserRate, methods: [patch] },
  { path: PET_ROUTES.petsCustomerById, methods: [get] },
  { path: PET_ROUTES.petsManageById, methods: [get] },
  { path: PRODUCT_ROUTES.productsByIdDisable, methods: [patch] },
  { path: PRODUCT_ROUTES.productsByIdEnable, methods: [patch] },
  { path: PRODUCT_ROUTES.productsByIdImages, methods: [get, put] },
  { path: PRODUCT_ROUTES.productsByIdMainInfo, methods: [get, put] },
  { path: PRODUCT_ROUTES.productsByIdUserRate, methods: [patch] },
  { path: PRODUCT_ROUTES.productsCustomerById, methods: [get] },
  { path: PRODUCT_ROUTES.productsManageById, methods: [get] },
  { path: PRODUCT_ROUTES.productsPropertyDefinitionsById, methods: [get] },
  { path: PRODUCT_ROUTES.productsWeightsById, methods: [get] },
  { path: USER_ROUTES.usersAddressesByAddressId, methods: [patch] },
  { path: USER_ROUTES.usersDisableById, methods: [put] },
  { path: USER_ROUTES.usersEnableById, methods: [put] },
  { path: USER_ROUTES.wishlistDeleteById, methods: [deleteMethod] },
  { path: BRAND_ROUTES.brandsEnabled, methods: [get] },
  { path: BREED_ROUTES.breedsPaginate, methods: [get] },
  { path: BREED_ROUTES.breedsRange, methods: [put] },
  { path: USER_ROUTES.cartAdd, methods: [post] },
  { path: USER_ROUTES.cartAll, methods: [get] },
  { path: USER_ROUTES.cartDeliveryWindow, methods: [patch] },
  { path: USER_ROUTES.cartDeliveryWindows, methods: [post] },
  { path: USER_ROUTES.cartEmpty, methods: [deleteMethod] },
  { path: DASHBOARD_ROUTES.dashboardMetrics, methods: [get] },
  { path: LANDING_ROUTES.landingPetTypes, methods: [get] },
  { path: LANDING_ROUTES.landingPetsPaginate, methods: [get] },
  { path: LANDING_ROUTES.landingProducts, methods: [get] },
  { path: LANDING_ROUTES.landingSearch, methods: [get] },
  { path: ORDER_ROUTES.ordersAll, methods: [get] },
  { path: PET_TYPE_ROUTES.petTypesRange, methods: [put] },
  { path: PET_ROUTES.petsPaginate, methods: [get] },
  { path: PRODUCT_ROUTES.productsPaginate, methods: [get] },
  { path: PRODUCT_ROUTES.productsPropertyDefinitions, methods: [put] },
  { path: PRODUCT_ROUTES.productsRange, methods: [put] },
  { path: USER_ROUTES.usersAddresses, methods: [post, get] },
  { path: USER_ROUTES.usersAll, methods: [get] },
  { path: USER_ROUTES.usersChangePassword, methods: [put] },
  { path: USER_ROUTES.usersCurrent, methods: [get] },
  { path: USER_ROUTES.usersEditInfo, methods: [put] },
  { path: USER_ROUTES.usersLogin, methods: [post] },
  { path: USER_ROUTES.usersLogout, methods: [post] },
  { path: USER_ROUTES.usersPaginate, methods: [get] },
  { path: USER_ROUTES.usersRefreshToken, methods: [post] },
  { path: USER_ROUTES.usersRegister, methods: [post] },
  { path: USER_ROUTES.usersResetPassword, methods: [post] },
  { path: USER_ROUTES.usersSendOtp, methods: [post] },
  { path: USER_ROUTES.usersVerify, methods: [post] },
  { path: USER_ROUTES.wishlistAdd, methods: [post] },
  { path: USER_ROUTES.wishlistAll, methods: [get] },
  { path: BRAND_ROUTES.brandsById, methods: [get, put, deleteMethod] },
  { path: BREED_ROUTES.breedsById, methods: [get, put, deleteMethod] },
  { path: CATEGORY_ROUTES.categoriesById, methods: [put, deleteMethod, get] },
  { path: LOCATION_ROUTES.citiesByProvinceId, methods: [get] },
  { path: ORDER_ROUTES.ordersById, methods: [get] },
  { path: PET_TYPE_ROUTES.petTypesById, methods: [get, put, deleteMethod] },
  { path: PET_ROUTES.petsById, methods: [put, deleteMethod] },
  { path: PRODUCT_ROUTES.productsById, methods: [put, patch, deleteMethod] },
  {
    path: SUB_CATEGORY_ROUTES.subCategoriesById,
    methods: [put, deleteMethod, get],
  },
  { path: USER_ROUTES.usersById, methods: [get, deleteMethod] },
  { path: BRAND_ROUTES.brands, methods: [get, post] },
  { path: BREED_ROUTES.breeds, methods: [get, post] },
  { path: CATEGORY_ROUTES.categories, methods: [post, get] },
  { path: COUNTRY_ROUTES.countries, methods: [get] },
  { path: IMAGE_ROUTES.images, methods: [post, deleteMethod] },
  { path: ORDER_ROUTES.orders, methods: [post, get] },
  { path: OTP_CODE_ROUTES.otpCode, methods: [post] },
  { path: PET_TYPE_ROUTES.petTypes, methods: [get, post] },
  { path: PET_ROUTES.pets, methods: [get, post] },
  { path: PRODUCT_ROUTES.products, methods: [get, post] },
  { path: LOCATION_ROUTES.provinces, methods: [get] },
  { path: REVERSE_GEOCODING_ROUTES.reverseGeocode, methods: [get] },
  { path: SUB_CATEGORY_ROUTES.subCategories, methods: [post, get] },
  { path: USER_ROUTES.users, methods: [post] },
];
